import XCTest

@testable import Web5

class VP1BVerifierTests: XCTestCase {

    func testVerifyQrCodeText_ValidQRCode() throws {
        let validQRCodeText = "VP1-B3ECQDIYACEMHIGDODB6KQAMDCELBIGDQQIBVBIRXWSRP46SGK63XJ4WBTA2XR5QYOKSRQ5AYSYMLMGTGY5A7MGF6DDCBRQCYIF5HRINVLSSGYN7DAQKLPG7OJZFQOMV6SPRNMCVVAPPLTJXIF5KKO5L4EVW6QIHTWXATK2OPGURQ5XDXBS5HEYKBOQBNIC5NRG64E5GKBAMMFAYZAQAVQIXNAHRBLZWZVHXBYO6AKQARBE6FTCCQBZEZIQ67FYTDR4OJFBCHEMBN6WBC5UA6EFPG3GU64HB3YBKACEETYWMIKAHETFCD34XCMOHRZEUEI4RQFXYYOWBBQ3AYQIMJ5IQYRJMFO6WZAUA2IAAVDBVBQZAYNRFHVWIFAGRAAFQYPQKRQ3SYHN5AAAOABTBGZWGPOB3BUTVEFS4U6CXMVFSGVZDD7STZCEQC4BHZQJ2NGFVEUI3TYEGFT4D66QQ4GQIAMLT6WHG6ZVZKXB4FDCKBKGFCDJUAHKPUDCSBUZWHIH3BRKECDECACWBC5UA6EFPG3GU64HB3YBKACEETYWMIKAHETFCD34XCMOHRZEUEI4RQFXY"

        let vp1b = try VP1BVerifier.verifyQRCode(qrcode: validQRCodeText)

        if let jsonData = try? JSONSerialization.data(withJSONObject: vp1b.expanded(), options: .prettyPrinted),
           let jsonString = String(data: jsonData, encoding: .utf8) {
            print(jsonString)
        }

        XCTAssertNotNil(vp1b.credential, "The credential should not be nil.")
    }

    func testVerifyIssuer_InvalidIssuer() async throws {
        let validQRCodeText = "VP1-B3ECQDIYACEMHIGDODB6KQAMDCELBIGDQQIBVAGEOQRICNHQR5O2ULU3JFTZVHGAYOKSRQ5AYSYMLMGTBB36NUGF6DDCBRQCYIF5LYJB7VTXLGIZHZ6FP5B7X556XIOMDYWEO6PIGYWPRJEKPB2QJNWBW637IEAWAP544RL7Q6ZSNE5WTP4LQ523UFZBFGNH5BASK6JXGBQMMFAYZAQAVQIXNAFMX2WWF3ZONWCHPZQUYKDPQ2P6JGUMQXBXKXPVV5MDIQTNWUOXOYWBC5UAVS7K2YXPFZWYI57GCTBIN6DJ7ZE2RSC4G5K56WXVQNCCNW2R253AYOWBBQ3AYQIMJ5IQYRJMFG6WZAUA2IAIVBECAOST23ECQDIQBCYCRQQIILA5XUAAAVPLEEDLCRRJSC5XPBXLSBX3UQJELQCGUXFBFZD2FVNCLKAU75LFCPDKPZUWURTPWC762YD4ZNALVP7EN45FP3JJOEQMJIFIYUINGBVHE64MKIGTALONPOGFIQIMQIAKYELWQCWL5LLC54XG3BDX4YKMFBXYNH7ETKGILQ3VLX226WBUIJW3KHLXM"

        do {
            let vp1b = try VP1BVerifier.verifyQRCode(qrcode: validQRCodeText)

            _ = try await VP1BVerifier.verifyIssuer(credential: vp1b.credential)

            XCTFail("Expected an invalid issuer error but did not receive one.")
        } catch let error as VP1BIssuers.Error {
            XCTAssertEqual(error, .issuerNotFound, "Expected invalid issuer error.")
        } catch {
            XCTFail("Unexpected error: \(error)")
        }
    }
}
