name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9"
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
    - name: Hash test vector inputs
      run: |
        if ! which sha25sum; then brew install coreutils; fi
        sha256sum $(find test-vectors -name '*.json') > test-vector-hashes.txt
    - uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          tests.xml
          test-vector-hashes.txt
